float64 temprature
bool are_motors_ready
string dubug_message



# This message file defines the hardware status information.

# 1. We create this message file (HardwareStatus.msg) to define the hardware data structure.
# 2. We add this message file to CMakeLists.txt so ROS2 knows to compile it.
# 3. Dependencies are listed in package.xml to provide necessary build and runtime tools.
# 4. When we run colcon build, ROS2 auto-generates C++ and Python code from this message.
# 5. This generated code is used in ROS2 nodes for publishing and subscribing hardware status messages.
